### ISSUE TITLE
Wish: should work with wcheck-mode

### ISSUE THREAD

**Issue by GregorZattler** [tmalsburg/guess-language.el#8]
Since I use wcheck-mode instead of flycheck I wish for supporting wcheck-mode.

I switched from flyspell to wcheck-mode because it uses vastly less ressources.

[https://github.com/tlikonen/wcheck-mode](https://github.com/tlikonen/wcheck-mode)

**Comment by tmalsburg** [comment]
I didn't know Wcheck.  Looks interesting but I don't have to the time to familiarize myself with it.  Pull request are welcome, though.

**Comment by tmalsburg** [comment]
We should have some infrastructure for notifying all kinds of modes when the detected language changes.  Hard-coding support for every spell-checker and whatnot is not desirable.  Users should be able to easily add support for whatever they want.

**Comment by GregorZattler** [comment]
I know the first few things only about elisp.  Therefore I cannot help with this.  A quick search of the emacs manual shows zero support for language changes in buffers.  The infrastructure would be a hook which is run when a checker dosn't know a word and a hook which is run when a language change is detected?

**Comment by tmalsburg** [comment]
Yes, regarding the hooks.  I'll think about how to make this as general and easy to configure as possible but I can't promise that there will be a result soon.

**Comment by tmalsburg** [comment]
I have a new version which should make it very easy to make guess-language work with wcheck (and other spell checkers) but it's not quite yet ready for prime time.  See also #11.

**Comment by tmalsburg** [comment]
We now have some basic infrastructure for configuring guess-language to work with other spell checkers.  I'm not familiar with wcheck, does it have a hook like a Flyspell's `flyspell-incorrect-hook`?  We need this to trigger guess-language when an incorrect word is detected.

**Comment by tmalsburg** [comment]
I played a little but with wcheck.  I like the ideas behind it (configurability) but it is lacking some of Flyspell's features that are really nice to have in the present context.  Most importantly, it's lacking a hook for the situation when an incorrect word is detected.  When using guess-language with Flyspell, we guess the language every time Flyspell doesn't recognize a word.  This is nice because as along as the user is typing correct words, guess-language doesn't have to do anything.  Since wcheck doesn't have such a hook, it's not clear when we should guess the language. We could guess when the buffer is opened but when a new file is created, there would be no text to use for guessing.  The user could trigger guessing manually but that would defy the purpose of guess-language which is to automatically select the correct language without having to bother the user.

Another issue is that wcheck seems to always check the complete document.  Hence, we can't deal with multiple languages in one document as we can with Flyspell.  Perhaps there are solutions for these problems but I don't have the time to think about it.  My strong suggestion is to use Flyspell but if you decide to stick with wcheck you can use the following code:

``` elisp
(defun guess-language-switch-wcheck-function (lang beginning end)
  "Switch the wcheck dictionary.

This is only done if the new language is different from the
previous language.  Otherwise, nothing happens.

LANG is the ISO 639-1 code of the language (as a
symbol).  BEGINNING and END are ignored since wcheck-mode has no
support for checking regions."
  (let* ((old-dictionary (cadr (assq guess-language-current-language guess-language-langcodes)))
         (new-dictionary (cadr (assq lang guess-language-langcodes))))
    (unless (string= old-dictionary new-dictionary)
      (wcheck-change-language new-dictionary))))

(remove-hook 'guess-language-after-detection-functions #'guess-language-switch-flypell-function)
(add-hook 'guess-language-after-detection-functions #'guess-language-switch-wcheck-function)
```

Then you can do `M-x guess-language` and it will detect the language of the current paragraph and then change the dictionary in wcheck (plus typo-mode settings if typo-mode is being used).  For the reasons explained above, there won’t be any automatic guessing.

Make sure you configure `guess-language-langcodes` such that it uses the names of the languages used in wcheck.

**Comment by GregorZattler** [comment]
Thank you very much for looking into this and providing your part of a generic infrastructure for language changes. 

>  Most importantly, it's lacking a hook for the situation when an incorrect word is detected.

I'll ask wcheck-modes developer if it's possible to have such a hook.

> Another issue is that wcheck seems to always check the complete document. 

According to it's documentation it checks the part of the buffer which is visible in the current window.  This is also what I experience when using it.  This is nice performacewise but perhaps this makes it difficult to provide the needed hook, though.

> but if you decide to stick with wcheck you can use the following code:

Thank you very much for providing this code.  I woudn't be able to do it myself.  I will try this in the next few days.

**Comment by tmalsburg** [comment]
Good idea to contact the authors of wcheck.  I'm sure they will be able to give us some useful hints.

> According to it's documentation it checks the part of the buffer which is visible in the current window. 

True, but it's the same problem though.  Languages change (if at all) on a paragraph-by-paragraph basis.  Regarding performance, Flyspell (when used with guess-language) checks only the word that is currently being typed and when the detected language changes it only rechecks the current paragraph.  Performance-wise this is pretty efficient.
